# Generated by Django 2.2.14 on 2020-12-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, null=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=64, null=True, verbose_name='패스워드')),
                ('author', models.CharField(max_length=64, null=True, verbose_name='사용자 이름')),
            ],
        ),
    ]
