# Generated by Django 3.1.2 on 2020-11-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=64, null=True, verbose_name='이메일'),
        ),
    ]
