# Generated by Django 3.1.2 on 2020-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201104_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='author',
            field=models.CharField(max_length=64, null=True, verbose_name='사용자 이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, null=True, verbose_name='패스워드'),
        ),
    ]
