name: sample-add-to-q

on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted, edited]

jobs:
  add_to_queue:
    env:
      SLACK_TOKEN: xoxb-2997279434613-4897081978066-mIVFSPNqUZ43v3Ivx9OZ0JLD
    runs-on: ubuntu-latest
    name: Add PR to queue
    steps:
      - name: Add PR to queue
        uses: lwhiteley/slack-merge-queue@v2.0.0
        id: add_to_q
        with:
          mode: 'INIT'
          channel: 'merge-queue'
          init_trigger: '/merging'
      # Use the output from the `add_to_q` step
      - name: Get the output
        run: echo "status => ${{ steps.add_to_q.outputs.status }}"
